# -*- coding: utf-8 -*-
"""bertina_internal1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4WRhwGkHDcfHYd_ZRwb87RPQFFRcmfR

**LAB 1**
"""

# 1
length = float(input("Please enter length of the triangle "))
breadth = float(input("Please enter breadth of the triangle "))
area = round((length * breadth),2)
print(f"The area of the triangle is {area}")

# 2
kg, m = input("Please enter weight in kg and height in m comma separated\n").split(",")
kg = float(kg)
m = float(m)

bmi = round(kg/pow(m,2),2)
if bmi <= 18.4:
    print("Underweight! Gain weight man")
elif bmi <= 24.9:
    print("Normal weight")
elif bmi <= 39.9:
    print("Over weight")
else:
    print("Obese! Lose weight man")

# 3
n = int(input("Enter number of students : "))
student_scores = {}
for i in range(n):
  student, score = input("Enter student name and score comma separated : ").split(",")
  score = int(score)
  student_scores[student] = score
for key, val in student_scores.items():
  print(key, val)

"""**LAB 2**"""

# 4
# minor, adult, senior
flag = True
while flag:
  age = int(input("Enter age : "))
  if age<=18:
    print(f"You're only {age}, you are a minor")
  elif age<=39:
    print(f"You're {age}, you are an adult")
  else:
    print(f"You are a senior, what's the secret to becoming {age}?")
  user = input("Enter y if there's another age you'd like to check else select n").lower()
  if user=='n':
    flag = False

# 5
for i in range(2,51,2):
  print(i)

#6

passwords = {
   "Berty" : "1234",
   "Divi" : "5678"
             }

flag = True
while flag:
    user_id = input("Please enter the user id : ")
    user_pass = input("Enter user password : ")
    if passwords[user_id] == user_pass:
      flag = False

"""**LAB 3**"""

#7
#avg of list of num
def avg_list():
  n = int(input("Enter the length of the list : "))
  my_list = []
  sum = 0
  for i in range(n):
    a = int(input("Enter the element: "))
    my_list.append(a)
    sum += a
  avg = round((sum/n),2)
  print(f"The average is {avg}")
flag = True
while flag:
  avg_list()
  user = input("Would you like to calculate average of a list again? y for yes and n for no : ").lower()
  if user=='n':
    flag = False

#8
#count vowels
def count_vowels():
  vowels = ['a','e','i','o','u']
  my_str = input("Enter your string : ").lower()
  count = 0
  for ch in my_str:
    if ch in vowels:
      count = count + 1
  print(f"The count of vowels in given string {my_str} is {count}")
flag = True
while flag:
  count_vowels()
  user = input("Would you like to calculate average of a list again? y for yes and n for no : ").lower()
  if user=='n':
    flag = False

#9
import datetime as dt
# current date and time print in python using datetime
print(f"The current date and time is {dt.datetime.now()}")

"""**LAB 4**"""

#10
def add(x,y):
  return x + y
x = 5
y = "Hello"
try:
  add(x,y)
except TypeError:
  print("Bro, how can you even add numbers and alphabets?")

#11
import math
x = -10
try:
  math.sqrt(x)
except ValueError:
  print("Warning! Please check your input properly")

#12
def div(x,y):
  return x / y
x = 5
y = 0
try:
  div(x,y)
except ZeroDivisionError:
  print("Bro, how can you even divide by 0?")

"""**LAB 5**"""

#13
with open("hello.txt","w") as file:
  file.write("Hello, Python!")

#14
with open("hello.txt") as file:
  reading_file = file.read()
print(reading_file)

#15
file = open("hello.txt",'a')
file.write("well well well")
file.close()
file = open("hello.txt")
p = file.read()
file.close()
print(p)